---
- name: Converge
  hosts: all
  become: true
  vars:
    pip_install_packages:
      - name: docker
    gitlab_external_url: https://mysite
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - ansible-role-gitlab
